### ISSUE TITLE
Reopening app in macOS error

### ISSUE THREAD

**Issue by behdadahmadi** [Meadowcottage/devRant#17]
![screen shot 2017-04-07 at 9 23 14 pm](https://cloud.githubusercontent.com/assets/17945460/24811084/eb47171e-1bd9-11e7-8356-b47f788624bc.png)
It seems in the "main.js" file you have an undefined object and Electron can't show the window.

**Comment by Meadowcottage** [comment]
I'm aware of this issue. It has been fixed since the `1.0.3` release and will be in the next update 😄 

The fix has already been added into the repo. If you wish to hack it in yourself, you're welcome to. [app/main.js](https://github.com/Meadowcottage/devRant/blob/master/app/main.js#L127-L129)
