### ISSUE TITLE
Paypal.me isn’t available everywhere

### ISSUE THREAD

**Issue by vitorgalvao** [Meadowcottage/devRant#5]
Just as a heads up, you might be limiting your reach by using paypal.me ([list of countries](https://www.paypal.me/pages/countries)).
![image](https://cloud.githubusercontent.com/assets/1699443/16821028/066963d2-494c-11e6-8182-d89574ed15d5.png)

**Comment by Meadowcottage** [comment]
Ah, thanks for the heads up. Gonna fix push a fix for this now.

**Comment by Meadowcottage** [comment]
Pushed a fix for this last night. Should be fixed now.
